name: Terraform apply

on:
  push:
    branches: [main]
    paths:
      - infra/envs/**

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs: 
      json: ${{ steps.detect-changes.outputs.json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Detect changes
        id: detect-changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'infra/envs/**')
          direct_roots=()

          for file in $changed_files; do
            if [[ "$file" == infra/envs/* ]]; then
              dir=$(dirname "$file")
              
              while [[ "$dir" != "infra/envs" && ! -f "$dir/backend.tf" ]]; do
                dir=$(dirname "$dir")
              done
              
              if [[ -f "$dir/backend.tf" ]]; then
                direct_roots+=("$dir")
              fi
            fi
          done

          direct_roots=($(printf "%s\n" "${direct_roots[@]}" | sort -u))

          entries="[]"
          for dir in "${direct_roots[@]}"; do
            case "$dir" in
              infra/envs/dev/*) env="dev" ;;
              infra/envs/prod/*) env="prod" ;;
              infra/envs/global) env="global" ;;
              *) continue ;;
            esac
            entries=$(echo "$entries" | jq -c --arg dir "$dir" --arg env "$env" '. += [{"dir":$dir,"environment":$env}]')
          done

          echo "json=$entries" >> "$GITHUB_OUTPUT"

  apply:
    name: Apply changes
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.json != '[]'
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-changes.outputs.json) }}
    environment: ${{ matrix.environment}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      
      - name: Initialize terraform
        run: terraform init -no-color
        working-directory:

      - name: Terraform apply
        run: terraform apply --auto-approve -no-color
        working-directory:


