name: Terraform lint

on:
  push:
    paths:
      - infra/**

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup terraform linter
        uses: terraform-linters/setup-tflint@v6
      
      - name: Show version
        run: tflint --version
      
      - name: Initialize linter
        run: tflint --init

      - name: Run linter
        run: tflint -f compact