name: Terraform security scan

on:
  push:
    branches-ignore: main
    paths:
      - infra/**

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run security scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: --config-file ../.tfsec.yaml